// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwvvmzksldywmyqfoayn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dnZtemtzbGR5d215cWZvYXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4ODg2MzcsImV4cCI6MjA1MDQ2NDYzN30.HMaKjb64xvBM-wrYoGDu_9SUzCvIVmPOpBubMtfuBbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);